#!/usr/bin/env bash
set -e

type=$1

clean_files() {
  files=(
    "/etc/ld.so.conf.d/intel-lib64.conf"
    "/etc/ld.so.conf.d/nvidia-lib64.conf"
    "/etc/X11/xinit/xinitrc.d/nvidia"
    "/etc/X11/xorg.conf.d/99-nvidia.conf"
    "/etc/X11/xorg.conf"
  )

  for file in "${files[@]}"; do
    if [ -h "$file" ]; then
      printf "Deleting %s\n" "$file"
      rm -f "$file"
    elif [ -f "$file" ]; then
      printf "Backing up %s\n" "$file"
      cp "$file" "$file.bak"
      rm -f "$file"
    fi
  done
}

case $type in
  nvidia)
    clean_files

    # setup xorg config
    src='/etc/fedora-prime/xorg.nvidia.conf.template'
    dst='/etc/fedora-prime/xorg.nvidia.conf'
    export PCI_ID
    PCI_ID="$(nvidia-xconfig --query-gpu-info | grep -i "PCI BusID" | awk '{print $4}')"
		eval "cat <<-EOF
		$(cat $src)
		EOF" > $dst

    printf "Linking..\n"
    ln -s /etc/fedora-prime/ld.nvidia.conf /etc/ld.so.conf.d/nvidia-lib64.conf
    ln -s /etc/fedora-prime/xinitrc.nvidia /etc/X11/xinit/xinitrc.d/nvidia
    ln -s /etc/fedora-prime/xorg.nvidia.conf /etc/X11/xorg.conf

    printf "Running ldconfig..\n"
    ldconfig
  ;;
  intel)
    clean_files

    printf "Linking..\n"
    ln -s /etc/fedora-prime/ld.intel.conf /etc/ld.so.conf.d/intel-lib64.conf

    printf "Running ldconfig..\n"
    ldconfig
    ;;
  * )
   printf "Usage: %s nvidia|intel\n" "$0"
   exit
   ;;
esac
